<a href="https://colab.research.google.com/github/Sankarlal-MyGH/Word-Embedding/blob/main/WordEmbeddingUsingKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
#vocalbulary size
voc_size = 100

In [5]:
One_hot_rep = [one_hot(words,voc_size)for words in sent]

In [6]:
One_hot_rep

[[97, 14, 73, 55],
 [97, 14, 73, 7],
 [97, 81, 73, 9],
 [6, 22, 57, 48, 51],
 [6, 22, 57, 48, 30],
 [13, 97, 44, 73, 83],
 [19, 61, 8, 48]]

In [7]:
#import tensorflow libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
#Initialize the length of the padded matrix
sent_length = 8

In [12]:
embedded_docs = pad_sequences(One_hot_rep,maxlen=sent_length,padding='pre')
print(embedded_docs)

[[ 0  0  0  0 97 14 73 55]
 [ 0  0  0  0 97 14 73  7]
 [ 0  0  0  0 97 81 73  9]
 [ 0  0  0  6 22 57 48 51]
 [ 0  0  0  6 22 57 48 30]
 [ 0  0  0 13 97 44 73 83]
 [ 0  0  0  0 19 61  8 48]]


In [14]:
#Declare the dimensions/features for the word embedding matrix
dim=15