<a href="https://colab.research.google.com/github/Sankarlal-MyGH/Word-Embedding/blob/main/WordEmbeddingUsingKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
#vocalbulary size
voc_size = 100

In [5]:
One_hot_rep = [one_hot(words,voc_size)for words in sent]

In [6]:
One_hot_rep

[[97, 14, 73, 55],
 [97, 14, 73, 7],
 [97, 81, 73, 9],
 [6, 22, 57, 48, 51],
 [6, 22, 57, 48, 30],
 [13, 97, 44, 73, 83],
 [19, 61, 8, 48]]

In [7]:
#import tensorflow libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
#Initialize the length of the padded matrix
sent_length = 8

In [12]:
embedded_docs = pad_sequences(One_hot_rep,maxlen=sent_length,padding='pre')
print(embedded_docs)

[[ 0  0  0  0 97 14 73 55]
 [ 0  0  0  0 97 14 73  7]
 [ 0  0  0  0 97 81 73  9]
 [ 0  0  0  6 22 57 48 51]
 [ 0  0  0  6 22 57 48 30]
 [ 0  0  0 13 97 44 73 83]
 [ 0  0  0  0 19 61  8 48]]


In [14]:
#Declare the dimensions/features for the word embedding matrix
dim=15

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 15)             1500      
Total params: 1,500
Trainable params: 1,500
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

[[[ 2.63755955e-02  3.57728340e-02 -5.33800200e-03  2.95386426e-02
   -1.75064430e-02  2.32119448e-02  3.69725488e-02  4.25342359e-02
    4.39226739e-02  4.76086251e-02 -1.01753324e-03  3.45900543e-02
    3.44105810e-03  4.17675637e-02 -3.91852260e-02]
  [ 2.63755955e-02  3.57728340e-02 -5.33800200e-03  2.95386426e-02
   -1.75064430e-02  2.32119448e-02  3.69725488e-02  4.25342359e-02
    4.39226739e-02  4.76086251e-02 -1.01753324e-03  3.45900543e-02
    3.44105810e-03  4.17675637e-02 -3.91852260e-02]
  [ 2.63755955e-02  3.57728340e-02 -5.33800200e-03  2.95386426e-02
   -1.75064430e-02  2.32119448e-02  3.69725488e-02  4.25342359e-02
    4.39226739e-02  4.76086251e-02 -1.01753324e-03  3.45900543e-02
    3.44105810e-03  4.17675637e-02 -3.91852260e-02]
  [ 2.63755955e-02  3.57728340e-02 -5.33800200e-03  2.95386426e-02
   -1.75064430e-02  2.32119448e-02  3.69725488e-02  4.25342359e-02
    4.39226739e-02  4.76086251e-02 -1.01753324e-03  3.45900543e-02
    3.44105810e-03  4.17675637e-02 -3.91

In [19]:
embedded_docs[0]

array([ 0,  0,  0,  0, 97, 14, 73, 55], dtype=int32)

In [20]:
print(model.predict(embedded_docs)[0])

[[ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [-0.00572071 -0.00976549 -0.01429636 -0.04909725 -0.02702143  0.00353717
   0.00810289 -0.0427964   0.0423154  -0.03928202 -0.00815814  0.04576402
  -0.02840469 -0.03782403 -0.02229691]
 [ 0.0020978  -0.00512366 -0.03282099  0.02804876  0.02791388 -0.

In [21]:
print(model.predict(embedded_docs)[1])

[[ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [ 0.0263756   0.03577283 -0.005338    0.02953864 -0.01750644  0.02321194
   0.03697255  0.04253424  0.04392267  0.04760863 -0.00101753  0.03459005
   0.00344106  0.04176756 -0.03918523]
 [-0.00572071 -0.00976549 -0.01429636 -0.04909725 -0.02702143  0.00353717
   0.00810289 -0.0427964   0.0423154  -0.03928202 -0.00815814  0.04576402
  -0.02840469 -0.03782403 -0.02229691]
 [ 0.0020978  -0.00512366 -0.03282099  0.02804876  0.02791388 -0.